version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    deploy:
      restart_policy:
        delay: 5s
        condition: any
    environment:
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    deploy:
      restart_policy:
        delay: 5s
        condition: any
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:22181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:19092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  sensor:
    image: faviouz/fleetit-sensor:latest
    deploy:
      replicas: 5
      restart_policy:
        delay: 15s
        condition: any
    environment:
      KAFKA_CLUSTER: "kafka:19092"

  websocket:
    image: faviouz/fleetit-websocket:latest
    deploy:
      restart_policy:
        delay: 5s
        condition: any
    ports:
      - "9999:9999"
    environment:
      KAFKA_CLUSTER: "kafka:19092"

  client:
    image: faviouz/fleetit-client-development:latest
    deploy:
      restart_policy:
        delay: 5s
        condition: any
    ports:
      - "80:3000"
    volumes:
      - ./client:/app

  postgres:
    image: faviouz/fleetit-postgres:latest
    deploy:
      restart_policy:
        delay: 5s
        condition: any
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "demo1234"
      POSTGRES_DB: "fleetit"

  api:
    image: faviouz/fleetit-api:latest
    deploy:
      restart_policy:
        delay: 5s
        condition: any
    ports:
      - "8080:8080"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "demo1234"
      POSTGRES_DB: "fleetit"
      POSTGRES_HOST: "postgres"

  alerts:
    image: faviouz/fleetit-alerts:latest
    deploy:
      restart_policy:
        delay: 5s
        condition: any
    environment:
      KAFKA_CLUSTER: "kafka:19092"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "demo1234"
      POSTGRES_DB: "fleetit"
      POSTGRES_HOST: "postgres"

  elasticsearch:
    image: faviouz/fleetit-elasticsearch:latest
    deploy:
      restart_policy:
        delay: 5s
        condition: any
    volumes:
      - ./monitoring/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

  metricbeat:
    image: faviouz/fleetit-metricbeat:latest
    user: root
    deploy:
      restart_policy:
        delay: 5s
        condition: any
    volumes:
       - ./monitoring/metricbeat/config/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
       - /var/run/docker.sock:/tmp/docker.sock

  kibana:
    image: faviouz/fleetit-kibana:latest
    deploy:
      restart_policy:
        delay: 5s
        condition: any
    volumes:
      - ./monitoring/kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"

  jenkins:
    image: faviouz/fleetit-jenkins:latest
    user: root
    deploy:
      restart_policy:
        delay: 5s
        condition: any
    volumes:
      - ./jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8082:8080"
      - "50000:50000"
