version: '2'
services:
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"
    kafka:
        image: wurstmeister/kafka
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
            KAFKA_ZOOKEEPER_CONNECT: 172.17.0.1:2181
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    api:
        build: api
        ports:
            - "1337:8080"
        depends_on:
            - kafka
    client:
        image: nginx:alpine
        volumes:
            - ./client:/usr/share/nginx/html
        ports:
            - "80:80"
        depends_on:
            - api

