spring:
  kafka:
    bootstrap-servers:
      - localhost:9092
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true
      group-id: healthcheck

  jackson.serialization.fail_on_empty_beans: false

server:
  session.timeout: 60
  connection-timeout: 100