language: java

sudo: false

install: true

addons:
  sonarqube:
    organization: "markush81-github"
    token:
      secure: "IP9Jz/MYj0e58upMCs2ncvLk/+2mfsVlxlWMC2/MFm4Ha/qyqYZjpE/+XsIweb9IyihsL0EQ6qw8jWPQXDW2v1IpUo0T4JtDDgVBYopPhFOdJgU//r/4k5qwZqO5yiaUgGP1dlgyko+JBExjkXzfGDsw3+xAmz8zAKTSAaMCxCJO0wgN3ctB45ak+u67uUUfeZvCp1pYt8BXzbItHMN3Tm8NZx30UaGgFpmTuyX7EEiKUIzKYeQAsazfN0DgrfQoKpB1MMpebh01dej5jAXTPq4iOlnn0n0ZIba/xj7C8xaKIPVOENFQ++CuAsPM8f60j/vZUhYreO+diaODw7ZBQ+YCjHrEMKvxTUuPpwkuIrXdABOgkCPFMVDFCNivShq6smPa3cEUdjGkUoGRrpuAPsVXvf4DhOJWZhXaqtFxw1oLQcTOQQWLBrF0fLWsNHbrNZs4FglX/ifbixNks6Kn5c5mcQ/mvujoXCYzFLZMpKMMmillxdz2rs5h8jyHOiSSudXqbLnST+E/570legY2oSX3bTUwzm9KSNvTlxImyEiNul41REogjycDz8lFYnQmI89X7QIVmrdz1PM+57qFm2MZbW01/PL1ifgOALn50FbWbfB6QxcaQAjRr92zblEcwkYQHgRNSDac5hz+y7zlZ4DOmnQX7WuRRRx5xvIPdeg="

jdk:
  - oraclejdk8

script:
  - ./gradlew sonarqube

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'

notifications:
  email: false